Algoritmo "mais menos multi"

Var
    A, B :inteiro
    mais, menos, vezes:inteiro


Inicio

      escreva("Digite o primeiro numero (A): ")
       leia(A)
      escreva("Digite o segundo numero (B): ")
       leia(B)
       
       mais <- (A+B)
       menos <- (A-B)
       vezes <- (A*B)

       escreval("o resultado da soma de A e B é: ", mais)
       escreval("o resultado da subtração de A e B é: ", menos)
       escreval("o resultado da multiplicação de A e B é: ", vezes)

Fimalgoritmo
