Algoritmo "semnome"
//
Var
   id: inteiro
   horas,valor:inteiro
   salario: real


Inicio
      escreva("Entre com o codigo do funcionario: ")
      leia(id)
      escreva("Digite o numero de horas trabalhadas: ")
      leia(horas)
      escreva("Digite o valor Hora: ")
      leia(valor)
      salario <-(horas*valor)
      escreval("O funcionario ",id)
      escreval("receberá:R$" ,salario)

Fimalgoritmo